apiVersion: v1
kind: Service
metadata:
  name: streams-guide
  labels:
    app: streams-guide
spec:
  #clusterIP: None
  selector:
    app: streams-guide
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streams-guide
  labels:
    app: streams-guide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streams-guide
  template:
    metadata:
      labels:
        app: streams-guide
    spec:
      containers:
      - name: streams-guide
        image: rhounkpe/streams-guide:1.0
        ports:
          - containerPort: 8080
